# Generated by Django 6.0.6 on 2026-06-07 03:59

import django.db.models.deletion
import django.utils.timezone
import panel.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=panel.models.generate_unique_id, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('city', models.CharField(choices=[('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Bangalore', 'Bangalore'), ('Pune', 'Pune'), ('Chennai', 'Chennai'), ('Hyderabad', 'Hyderabad'), ('Kolkata', 'Kolkata')], max_length=50)),
                ('category', models.CharField(choices=[('Healthcare', 'Healthcare'), ('Finance', 'Finance'), ('Retail', 'Retail'), ('FMCG', 'FMCG'), ('Technology', 'Technology'), ('Other', 'Other')], default='Other', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cooloff', 'Cool-off'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('referral_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cool_off_until', models.DateField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('ai_category', models.CharField(blank=True, max_length=50)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='panel.respondent')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='ReferralStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('lead', 'Lead'), ('fit', 'Fit'), ('completion', 'Completion')], default='lead', max_length=20)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_received', to='panel.respondent')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='panel.respondent')),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.survey')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('referrer', 'referred')},
            },
        ),
    ]
